# -*- coding: utf-8 -*-
"""Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxvOoJw_U4BoaGj0Fra-i448sljaCNO7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/ecommerce retail.xlsx', sheet_name='ecommerce retail')
df

#EDA
df.isna().sum()

df.drop(columns=['Description'], inplace=True)

df_rfm = df.dropna(subset = 'CustomerID').copy()
df_unknown = df[df['CustomerID'].isna()].copy()  # CustomerID is null

df_rfm.info()

df.info()

df_rfm['CustomerID']= df_rfm['CustomerID'].astype(int)
df_rfm

#Assumption
df_rfm2 = df_rfm.groupby(df_rfm['Country'], as_index = False).agg({'InvoiceNo': 'count'}).sort_values('InvoiceNo', ascending=False)
df_rfm2['percentage'] = round(100* df_rfm2['InvoiceNo']/len(df_rfm), 2)
df_rfm2

df_uk = df_rfm[df_rfm['Country'] == 'United Kingdom'].copy()
df_others = df_rfm[df_rfm['Country'] != 'United Kingdom'].copy()
df_uk

df_others_sales = df_others[df_others['Quantity'] > 0].copy()
df_others_sales.describe()

df_uk.describe()

df_uk_sales = df_uk[df_uk['Quantity'] > 0].copy()
df_uk_sales.describe()

recency = (
    df_uk_sales.groupby('CustomerID')['InvoiceDate']
    .max()
    .reset_index()
)
recency['Recency'] = (pd.to_datetime('2011-12-31') - pd.to_datetime(recency['InvoiceDate'])).dt.days
recency = recency[['CustomerID', 'Recency']]
recency

df_uk_sales['Monetary'] = df_uk_sales['Quantity'] * df_uk_sales['UnitPrice']
monetary = (
    df_uk_sales.groupby('CustomerID')['Monetary']
    .sum()
    .reset_index()
)
monetary

frequency = (
    df_uk_sales.groupby('CustomerID')['InvoiceNo']
    .nunique()
    .reset_index()
    .rename(columns={'InvoiceNo': 'Frequency'})
)
frequency

#Calculate RFM
rfm_uk = recency.merge(frequency, on='CustomerID').merge(monetary, on='CustomerID')
rfm_uk.describe()

# (RFM)Divide results by levels 1,2,3,4,5
# R_score
rfm_uk['R_score'] = pd.qcut(rfm_uk['Recency'], 5, labels=[5,4,3,2,1], duplicates='drop')

# F_score
rfm_uk['F_score'] = pd.cut(
    rfm_uk['Frequency'],
    bins=[0, 1, 3, 5, 10, rfm_uk['Frequency'].max()],
    labels=[1, 2, 3, 4, 5],
    include_lowest=True
)

# M_score
rfm_uk['M_score'] = pd.cut(
    rfm_uk['Monetary'],
    bins=[0, 300, 650, 1600, 5000, rfm_uk['Monetary'].max()],
    labels=[1, 2, 3, 4, 5],
    include_lowest=True
)

# RFM
rfm_uk['RFM'] = rfm_uk['R_score'].astype(str) + rfm_uk['F_score'].astype(str) + rfm_uk['M_score'].astype(str)

rfm_uk

# segmentation
segment_dict = {
    'Champions': ['555','554','544','545','454','455','445'],
    'Loyal': ['543','444','435','355','354','345','344','335'],
    'Potential Loyalist': ['553','551','552','541','542','533','532','531','452','451','442','441','431','453','433','432','423','353','352','351','342','341','333','323'],
    'New Customers': ['512','511','422','421','412','411','311'],
    'Promising': ['525','524','523','522','521','515','514','513','425','424','413','414','415','315','314','313'],
    'Need Attention': ['535','534','443','434','343','334','325','324'],
    'About To Sleep': ['331','321','312','221','213','231','241','251'],
    'At Risk': ['255','254','245','244','253','252','243','242','235','234','225','224','153','152','145','143','142','135','134','133','125','124'],
    'Cannot Lose Them': ['155','154','144','214','215','115','114','113'],
    'Hibernating': ['332','322','233','232','223','222','132','123','122','212','211'],
    'Lost customers': ['111','112','121','131','141','151']
}

def seg(data):
  for segment , score in segment_dict.items():
    if data in score:
      return segment

rfm_uk['Segment'] = rfm_uk['RFM'].apply(seg)

rfm_uk # Customers from the UK

country = df_others_sales[['CustomerID','Country']].drop_duplicates()
 country

country_counts = df_others_sales.groupby('CustomerID')['Country'].nunique().reset_index()
multi_country_customers = country_counts[country_counts['Country'] > 1]
multi_country_customers

details = df_others_sales[df_others_sales['CustomerID'].isin(multi_country_customers['CustomerID'])]
details.sort_values(['CustomerID', 'InvoiceDate'])

# Other countries
recency_2 = (
    df_others_sales.groupby('CustomerID')['InvoiceDate']
    .max()
    .reset_index()
)
recency_2['Recency'] = (pd.to_datetime('2011-12-31') - pd.to_datetime(recency_2['InvoiceDate'])).dt.days
recency_2 = recency_2[['CustomerID', 'Recency']]

frequency_2 = (
    df_others_sales.groupby('CustomerID')['InvoiceNo']
    .nunique()
    .reset_index()
    .rename(columns={'InvoiceNo': 'Frequency'})
)

df_others_sales['Monetary'] = df_others_sales['Quantity'] * df_others_sales['UnitPrice']
monetary_2 = (
    df_others_sales.groupby('CustomerID')['Monetary']
    .sum()
    .reset_index()
)

# merge
rfm_others = recency_2.merge(frequency_2, on='CustomerID').merge(monetary_2, on='CustomerID')

# (RFM)Divide results by levels 1,2,3,4,5
# R_score
rbins = pd.qcut(rfm_others['Recency'], 5, retbins=True)[1]
rfm_others['R_score'] = pd.cut(rfm_others['Recency'], bins=rbins, labels=[5,4,3,2,1], include_lowest=True)

# F_score
rfm_others['F_score'] = pd.cut(
    rfm_others['Frequency'],
    bins=[0, 1, 3, 5, 10, rfm_others['Frequency'].max()],
    labels=[1, 2, 3, 4, 5],
    include_lowest=True
)

# M_score
rfm_others['M_score'] = pd.cut(
    rfm_others['Monetary'],
    bins=[0, 300, 650, 1600, 5000, rfm_others['Monetary'].max()],
    labels=[1, 2, 3, 4, 5],
    include_lowest=True
)

# RFM
rfm_others['RFM'] = rfm_others['R_score'].astype(str) + rfm_others['F_score'].astype(str) + rfm_others['M_score'].astype(str)

def seg(data):
  for segment , score in segment_dict.items():
    if data in score:
      return segment
rfm_others['Segment'] = rfm_others['RFM'].apply(seg)

rfm_others # Analyze by 'customer' not include 'country' - one row per customer (all countries combined)

# recency
recency_3 = (
    df_others_sales.groupby(['CustomerID', 'Country'])['InvoiceDate']
    .max()
    .reset_index()
)
recency_3['Recency'] = (pd.to_datetime('2011-12-31') - pd.to_datetime(recency_3['InvoiceDate'])).dt.days
recency_3 = recency_3[['CustomerID', 'Country', 'Recency']]

# frequency
frequency_3 = (
    df_others_sales.groupby(['CustomerID', 'Country'])['InvoiceNo']
    .nunique()
    .reset_index()
    .rename(columns={'InvoiceNo': 'Frequency'})
)

# monetary
monetary_3 = (
    df_others_sales.groupby(['CustomerID', 'Country'])['Monetary']
    .sum()
    .reset_index()
)

# merge
rfm_others_country = (
    recency_3
    .merge(frequency_3, on=['CustomerID', 'Country'])
    .merge(monetary_3, on=['CustomerID', 'Country'])
)

# RFM
rfm_others_country['R_score'] = pd.cut(rfm_others_country['Recency'], bins=rbins, labels=[5,4,3,2,1], include_lowest=True)

rfm_others_country['F_score'] = pd.cut(
    rfm_others_country['Frequency'],
    bins=[0, 1, 3, 5, 10, rfm_others_country['Frequency'].max()],
    labels=[1, 2, 3, 4, 5],
    include_lowest=True
)

rfm_others_country['M_score'] = pd.cut(
    rfm_others_country['Monetary'],
    bins=[0, 300, 650, 1600, 5000, rfm_others_country['Monetary'].max()],
    labels=[1, 2, 3, 4, 5],
    include_lowest=True
)

rfm_others_country['RFM'] = (rfm_others_country['R_score'].astype(str)+ rfm_others_country['F_score'].astype(str)+ rfm_others_country['M_score'].astype(str))

def seg(data):
  for segment , score in segment_dict.items():
    if data in score:
      return segment
rfm_others_country['Segment'] = rfm_others_country['RFM'].apply(seg)

rfm_others_country # Analyze by country (one row per customer per country)

#rfm_uk
#rfm_others - Analyze by customer - one row per customer (all countries combined)
#rfm_others_country - Analyze by country (one row per customer per country)

seg_order = rfm_uk['Segment'].value_counts().index

plt.figure(figsize=(10,6))
ax = sns.countplot(
    x='Segment',
    data=rfm_uk,
    order=seg_order,
    hue='Segment',
    palette= 'Blues',
    legend=False
)

plt.title('Number of Customer Segmentation (UK)', fontsize=14, fontweight='bold')
plt.xlabel('Segmentation', fontsize=12)
plt.ylabel('Number of Customers', fontsize=12)
plt.xticks(rotation=45, ha='right')

# data label
for i in ax.containers:
    ax.bar_label(i, padding=2,fontsize=10)

plt.tight_layout()
plt.show()

total_customers =  rfm_uk['CustomerID'].nunique() + rfm_others['CustomerID'].nunique()
count_data = rfm_uk['Segment'].value_counts().reset_index()
count_data.columns = ['Segment', 'Customer Count']
count_data['Customer %'] = 100 * count_data['Customer Count'] / total_customers

def autopct_filter(pct):
    return f'{pct:.1f}%' if pct >= 2 else ''

# Tính góc bắt đầu cho mỗi lát (để biết lát nào là "Cannot Lose Them")
angles = 360 * count_data['Customer %'].cumsum() / 100 - (360 * count_data['Customer %'] / 200)
target_segment = "Cannot Lose Them"

if target_segment in count_data['Segment'].values:
    target_angle = angles[count_data['Segment'] == target_segment].values[0]
else:
    target_angle = 0

# Muốn lát đó nằm giữa bên phải (0°), thì startangle = -target_angle
start_angle = -target_angle

# Vẽ donut chart
plt.figure(figsize=(8,6))
wedges, texts, autotexts = plt.pie(
    count_data['Customer Count'],
    labels=count_data['Segment'],
    autopct=autopct_filter,
    startangle=start_angle,
    colors=sns.color_palette('Blues', len(count_data))[::-1],
    pctdistance=0.75,
    labeldistance=1.05,
    wedgeprops={'width':0.4}
)
plt.setp(autotexts, size=9)
plt.title('Customer Distribution by Segment (UK)', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# Tính tổng doanh thu theo nhóm
rev_segment = rfm_uk.groupby('Segment')['Monetary'].sum().reset_index().sort_values('Monetary', ascending=False)
rev_segment['Monetary_K'] = round(rev_segment['Monetary']/ 1000,2)

# Vẽ biểu đồ
plt.figure(figsize=(10,6))
ax = sns.barplot(
    data=rev_segment,
    x='Segment',
    y='Monetary_K',
    hue='Segment',
    legend = False,
    palette='viridis')

plt.title('Total Revenue by Customer Segment (UK)', fontsize=14, fontweight='bold')
plt.xlabel('Customer Segment', fontsize=12)
plt.ylabel('Total Revenue in USD (Unit: 1000)', fontsize=12)

# Thêm nhãn giá trị trên cột
for container in ax.containers:
    ax.bar_label(container, fontsize=10, padding=3)

plt.xticks(rotation=45, ha = 'right')
plt.tight_layout()
plt.show()

total_revenue = (df_rfm['Quantity'] * df_rfm['UnitPrice']).sum()
rev_segment['Revenue Share (%)'] = 100 * rev_segment['Monetary'] / total_revenue
range_stats = (
    rfm_uk.groupby('Segment')['Monetary']
    .agg(['min', 'max'])
    .reset_index()
)

# Gộp vào rev_segment
rev_segment = rev_segment.merge(range_stats, on='Segment', how='left')
rev_segment['Spending Range'] = (
    rev_segment['min'].astype(int).astype(str)
    + " - " +
    rev_segment['max'].astype(int).astype(str)
)
rev_segment

rev_segment['Segment_Label'] = rev_segment['Segment'] + '\n(' + rev_segment['Spending Range'] + ')'

# Sắp xếp theo doanh thu giảm dần
rev_segment = rev_segment.sort_values('Revenue Share (%)', ascending=False)

# Vẽ biểu đồ
plt.figure(figsize=(11, 6))
ax = sns.barplot(
    data=rev_segment,
    x='Revenue Share (%)',
    y='Segment_Label',
    hue='Segment',
    legend=False,
    palette='viridis'
)

plt.title('Revenue Contribution by Segment (UK vs Global Total)', fontsize=14)
plt.ylabel('Customer Segment (Spending Range)')
plt.xlabel('Revenue Share (%)')

# Thêm data labels hiển thị giá trị doanh thu
for container in ax.containers:
    ax.bar_label(container, fmt='%.1f%%', padding = 2, fontsize=9)

plt.tight_layout()
plt.show()

rfm_heatmap = rfm_uk.groupby(['R_score', 'F_score'], observed=False)['Monetary'].mean().unstack()

plt.figure(figsize=(8,6))
sns.heatmap(rfm_heatmap, cmap='Blues', annot=True, fmt='.0f')
plt.title('RFM Heatmap in UK (Avg Monetary by Recency-Frequency)')
plt.xlabel('R Score')
plt.ylabel('F Score')
plt.show()

seg_order_2 = rfm_others['Segment'].value_counts().index

plt.figure(figsize=(10,6))
ax = sns.countplot(
    x='Segment',
    data=rfm_others,
    order=seg_order_2,
    hue='Segment',
    palette= 'Blues',
    legend=False
)

plt.title('Number of Customer Segmentation (Other countries)', fontsize=14, fontweight='bold')
plt.xlabel('Segmentation', fontsize=12)
plt.ylabel('Number of Customers', fontsize=12)
plt.xticks(rotation=45, ha='right')

# data label
for i in ax.containers:
    ax.bar_label(i, padding=2,fontsize=10)

plt.tight_layout()
plt.show()

country_count = (
    rfm_others_country.groupby('Country', as_index=False)['CustomerID']
    .nunique()
    .rename(columns={'CustomerID': 'CustomerCount'})
    .sort_values(by='CustomerCount', ascending=False)
)

# Sắp thứ tự Country theo số lượng khách
seg_order = country_count['Country']

# Tạo dải màu xanh đậm -> nhạt dần
palette = sns.color_palette("Blues", n_colors=len(country_count))[::-1]

# Vẽ biểu đồ
plt.figure(figsize=(10,6))
ax = sns.barplot(
    x='Country',
    y='CustomerCount',
    data=country_count,
    order=seg_order,
    hue='Country',
    legend=False,
    palette=palette
)

plt.title('Number of Customers by Country (Global excluding UK)', fontsize=14, fontweight='bold')
plt.xlabel('Country', fontsize=12)
plt.ylabel('Number of Customers', fontsize=12)
plt.xticks(rotation=45, ha='right')

# Hiển thị giá trị trên cột
for container in ax.containers:
    ax.bar_label(container, fmt='%.0f', padding=3, fontsize=10)

plt.tight_layout()
plt.show()

rfm_share = (
    rfm_others_country
    .groupby(['Country', 'Segment'], as_index=False)
    .agg({'CustomerID': 'nunique'})
    .rename(columns={'CustomerID': 'CustomerCount'})
)

country_top5 = (
    rfm_share.groupby('Country')['CustomerCount']
    .sum()
    .sort_values(ascending=False)
    .head(5)
    .index
)

rfm_top5_seg = (
    rfm_share[rfm_share['Country'].isin(country_top5)]
    .sort_values(['Country', 'CustomerCount'], ascending=[True, False])
    .groupby('Country')
    .head(3)
)

country_order = (
    rfm_top5_seg.groupby('Country')['CustomerCount']
    .sum()
    .sort_values(ascending=False)
    .index
)

plt.figure(figsize=(10,6))
ax = sns.barplot(
    data=rfm_top5_seg,
    x='Country',
    y='CustomerCount',
    hue='Segment',
    order=country_order,
    palette='Set2',
    dodge=True,
    width=0.9
)

plt.title('Top 3 Customer Segments in Top 5 Countries (Global excluding UK)', fontsize=14, fontweight='bold')
plt.xlabel('Country', fontsize=12)
plt.ylabel('Number of Customers', fontsize=12)
plt.xticks(rotation=0)
plt.legend(title='Segment', bbox_to_anchor=(1.05, 1), loc='upper left')
ax.yaxis.get_major_locator().set_params(integer=True)

# Hiển thị nhãn số trên mỗi cột
for container in ax.containers:
    ax.bar_label(container, fmt='%d', fontsize=10, padding=3)

plt.tight_layout()
plt.show()

rev_segment2 = rfm_others.groupby('Segment')['Monetary'].sum().reset_index().sort_values('Monetary', ascending=False)
rev_segment2

rev_segment2['Monetary_K'] = round(rev_segment2['Monetary']/ 1000,2)

rev_segment2['Revenue Share (%)'] = 100 * rev_segment2['Monetary'] / total_revenue
range_stats2 = (
    rfm_others.groupby('Segment')['Monetary']
    .agg(['min', 'max'])
    .reset_index()
)

# Gộp vào rev_segment
rev_segment2 = rev_segment2.merge(range_stats, on='Segment', how='left')
rev_segment2['Spending_Range'] = (
    rev_segment2['min'].astype(int).astype(str)
    + " - " +
    rev_segment2['max'].astype(int).astype(str)
)
rev_segment2

# Doanh thu từng segment
revenue_by_segment = (
    rfm_others.groupby('Segment', as_index=False)
    .agg({'Monetary': 'sum'})
    .sort_values('Monetary', ascending=False)
)

# Tính tỷ trọng %
revenue_by_segment['RevenueShare'] = (revenue_by_segment['Monetary'] / total_revenue * 100).round(1)

# Format nhãn hiển thị thêm (min–max)
segment_summary = (
    rfm_others.groupby('Segment')['Monetary']
    .agg(['min', 'max'])
    .astype(int)
    .reset_index()
)

revenue_plot = revenue_by_segment.merge(segment_summary, on='Segment')

# Thêm nhãn hiển thị
revenue_plot['Segment_Label'] = (
    revenue_plot['Segment'] + '\n(' +
    revenue_plot['min'].astype(str) + ' - ' +
    revenue_plot['max'].astype(str) + ')'
)

# Vẽ biểu đồ
plt.figure(figsize=(12,6))
ax = sns.barplot(
    data=revenue_plot,
    y='Segment_Label',
    x='RevenueShare',
    palette='viridis'
)

# Tiêu đề và trục
plt.title('Revenue Contribution by Segment (Global excluding UK)', fontsize=14, fontweight='bold')
plt.xlabel('Revenue Share (%)', fontsize=12)
plt.ylabel('Customer Segment (Spending Range)', fontsize=12)

# Gắn nhãn %
for i, v in enumerate(revenue_plot['RevenueShare']):
    ax.text(v + 0.3, i, f'{v:.1f}%', va='center', fontsize=10)

plt.tight_layout()
plt.show()

